### PR TITLE
FAQ: add more frequently asked questions

### LINKED ISSUE #26: OKD project state and relation to OpenShift
I am deeply confused by the current state of OKD project. Until release of version 4, I thought that OpenShift was developed in an open source process typical for Red Hat - i.e. that OKD was the upstream project where development work was done and OpenShift Container Platform was the supported version, based on OKD code.

However, something has changed along with the release of OpenShift 4. I don't understand what is the current relation between OpenShift and OKD. There was no official OKD release for version 4, despite OpenShift already being at version 4.2. The OKD web page suggests that latest release was 3.11.

Could you please explain what is the current development model for OpenShift, and the relation between OKD and OpenShift?

### LINKED ISSUE #45: docs: describe how to ssh into FCOS images to troubleshoot
You can SSH into FCOS images to troubleshoot issues during initial deployment/bootstrap if you have direct access to the running machine. `ssh core@<ip address or hostname of VM>`. This is not documented anywhere except the old Container Linux CoreOS docs. It should probably be mentioned in these docs as well.

### PR DESCRIPTION
**Pull request by vrutkovs**
Update FAQ:
* Add Table Of Contents for easier navigation
* OKD-OCP relations
* Update improvements
* Troubleshooting

Fixes #26 
Fixes #45

### CODE REVIEW

**Comment by jomeier** [comment]
Hi Vadim,

I would like to see this questions answered:

Some OCP/OKD 4 functionality is provided with Operators from the Operator Hub. This matrix provides useful information about differences between OCP and OKD 4:

```         
---------------------------------------- OCP --------------------- OKD ----------------------------- Repositories -------------
OperatorHub catalogs                 Red Hat Operators             community
                                     Certified Operators           upstream-community (?)
                                     Red Hat Marketplace

Usage                                needs OCP subscription        free to use

Support                              Red Hat                       community

Operators (w. subscription/free)     OpenShift Service Mesh        Maistra                              github.com/maistra
                                     ElasticSearch                 <where is the community version?>    ?
                                     OpenShift Serverless          <is a community version available?>  ?
                                     Kiali                         Kiali                                ?
                                     Jaeger                        Jaeger                               ?
```

**Comment by vrutkovs** [comment]
Lets describe these differences in a new section - "How OKD cluster is different from an OCP cluster"?

**Comment by jomeier** [comment]
More Questions:
- how often will new minor versions of OKD 4 being released? (bi weekly)
- do I have to update from a rather old version to a newer version minor version after minor version or can I directly update to a destination version in one step?
- which Kubernetes Version is inside?
- how to install/update without the cluster having an internet connection (but an image mirror)
  - mirror images in private registry (oc adm mirror ...)
  - use ImageContentSourcePolicy CR or write a MachineConfig that directly sets mirrors in /etc/containers/registries.conf
- how to use OperatorHub / 3rd party images without rewriting manifests if my cluster has no internet connection (but an image mirror)
  - mirror images to private registry (docker pull / docker tag / docker push)
  - set mirrors in /etc/containers/registries.conf for docker.io/quay.io/... You can't use ImageContentSourcePolicy with images that are referenced by tag. Because of that we directly write to registries.conf.

**Comment by jomeier** [comment]
Upgrade / Backup / Restore:
- Which backup/restore strategy do you recommend? (current docs are not sufficient)
- What can I do if operators are degraded during an update and I must urgently get it working again?
- How can I revert an upgrade (not only images but also config files on the host and etcd) ?
  - how to revert rendered MachineConfigs, ... ?
  - in which directories on FCOS are files saved persistently?

**Comment by jomeier** [comment]
- Updates of operators in the OperatorHub. Community operators not always are built regularily. Can I build and publish them on my own (private registry or official OperatorHub) ?

**Comment by vrutkovs** [comment]
Let keep FAQ sections short. Disconnnected install and upgrades are described at docs.okd.io. If possible we should extend those. Same goes for backup/restore - that would be best described in the guide / blog post instead.

OperatorHub questions are out of scope for OKD really, we merely follow their updates

**Comment by jomeier** [comment]
Support:
- Is it allowed to use OKD 4 in production environments and can you recommend that (if the own team provides the support) ?
- Will it be possible to upgrade a cluster thats running on OKD 4 to OCP 4 and get support afterwards? (a constraint that OCP must support a special ignition version is ok, so everybody understands what to wait for)

**Comment by jomeier** [comment]
> Let keep FAQ sections short. Disconnnected install and upgrades are described at docs.okd.io. If possible we should extend those. Same goes for backup/restore - that would be best described in the guide / blog post instead.
> 
> OperatorHub questions are out of scope for OKD really, we merely follow their updates

To improve the official docs is ok.

Because some features that are tightly integrated in OCP 4 are only available with the OperatorHub we should lose a few words about that, too. The user experience of OCP/OKD is tightly coupled with this external ecosystem. I invested weeks for that! Don't want other users to suffer from that.

**Comment by vrutkovs** [comment]
>how often will new minor versions of OKD 4 being released? (bi weekly)

Addressed in b824d1e18a0d76ce48fa979d08e9ec374742c475

> do I have to update from a rather old version to a newer version minor version after minor version or can I directly update to a destination version in one step?

Addressed in f537eb39b7512190e05848c4c9228470a76f7008

>which Kubernetes Version is inside?

That's already in `How can I find out what's inside of a (CI) release and which commit id each component has?`. There is no static map right now anyway, say, 4.6 is currently 1.18-based but soon would be rebased on k8s 1.19

>What can I do if operators are degraded during an update and I must urgently get the system working again?

I don't think it fits FAQ, as there is no answer to such general question (depends on operator really)

> Will OKD 4 get an automatic backup/restore/rollback feature

"Will OKD4 have x feature" might be a good one - in general the answer is https://github.com/openshift/enhancement PRs

>Is it allowed to use OKD 4 in production environments and can you recommend that (if the own team provides the support) ?

Addressed in 4e6aa5ebe5fc46bc0c1261d6322a3d1974db99fa. Not sure if that addresses "allowed to use" - there are no direct restrictions (but plenty of indirect ones, coming from Fedora)


>Will it be possible to upgrade a cluster thats running on OKD 4 to OCP 4 and get support afterwards? 

That is not yet determined

**Comment by jomeier** [comment]
Maybe a few words about what "degraded" on an operator means, what "updating" means, makes sense.

"Updating" means that an operator tries to set its desired state (config has changed and it tries to recover it, it tries to update itself).

"Degraded" means (and happens during updates) not always that there is a real problem but after an update it can happen.

Operators that are in "Updating" state without currently updating OKD can confuse people. "Degraded" is the worst thing that can happen to you in an OKD 4 cluster. So it should definitely being addressed somewhere and how to recover from that.

A table with the names of the operators and what their purpose is and a link to typical error patterns would be awesome. I'm sure that you have something like that in your docs.

**Comment by vrutkovs** [comment]
>Maybe a few words about what "degraded" on an operator means, what "updating" means, makes sense.

Guess we could add this later. This however is not really OKD specific, so docs would be a better place for this

>A table with the names of the operators and what their purpose is and a link to typical error patterns would be awesome. I'm sure that you have something like that in your docs.

https://docs.okd.io/latest/operators/operator-reference.html?

**Comment by vrutkovs** [comment]
I'll go ahead and merge this as it adds a few useful hints for new users - and we can expand FAQ later

**Pull request merged**
