### PR TITLE
Updated URL to latest stable FCOS release

### PR DESCRIPTION
**Pull request by JaimeMagiera**
Probably best to update this regularly given the nascent state of the FCOS.

### CODE REVIEW

**Comment by vrutkovs** [comment]
This build is not yet being used by installer. It would work, but there would be a (small) discrepancy between IPI and UPI flow.

We're waiting for progress on official locations for GCP / Azure before bootimage is updated

**Comment by LorbusChris** [comment]
in general, instead of linking that specific build, we should find (or create) a `latest` URL

**Comment by JaimeMagiera** [comment]
That's a wise suggestion.

**Comment by LorbusChris** [comment]
I'll have a proper look shortly, just one thing already: Please rename the script to include vSphere and UPI in its path or name.

**Pull request closed without merging**
